version: "3.9"
services:
  dev:
    # Will build ./docker/Dockerfile
    # This Dockerfile is for GPU based development
    ipc: host
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
      - /home/ubuntu/.cache:/root/.cache
      - /home/ubuntu/.torch:/root/.torch
      - /home/ubuntu/.config:/root/.config
      - /home/ubuntu/.bash_history:/root/.bash_history
      - /home/ubuntu/.netrc:/root/.netrc
      - /home/ubuntu/Datasets:/root/Datasets
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
